apiVersion: apps/v1
kind: Deployment
metadata:
  name: addapppublic
  labels:
    app: add
spec:
  replicas: 1
  selector:
    matchLabels:
      app: addapppublic
  template:
    metadata:
      labels:
        app: addapppublic
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "addapppublic"
        dapr.io/app-port: "4000"
        dapr.io/config: "appconfig"
    spec:
      containers:
      - name: add
        image: idjohnson/coboladder:0.0.3
        env:
        - name: APP_PORT
          value: "4000"
        ports:
        - containerPort: 4000
        imagePullPolicy: Always


