apiVersion: apps/v1
kind: Deployment
metadata:
  name: addapp
  labels:
    app: add
spec:
  replicas: 1
  selector:
    matchLabels:
      app: add
  template:
    metadata:
      labels:
        app: add
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "addapp"
        dapr.io/app-port: "4000"
        dapr.io/config: "appconfig"
    spec:
      containers:
      - name: add
        image: harbor.freshbrewed.science/freshbrewedprivate/coboladder:0.0.3
        env:
        - name: APP_PORT
          value: "4000"
        ports:
        - containerPort: 4000
        imagePullPolicy: Always
      imagePullSecrets:
      - name: myharborreg


